apiVersion: v1
kind: Service
metadata:
  name: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - name: main
      port: 8086
      targetPort: 8086
    - name: admin
      port: 8088
      targetPort: 8088
  type: ClusterIP
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data
  labels:
    app: influxdb
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-claim
      containers:
      - name: influxdb
        image: service_influxdb
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: "/var/lib/influxdb"
            name: influxdb-storage